include (../app.pri)

QT += core gui printsupport xml

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

# You can make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

INCLUDEPATH += $$PWD/../Dpc $$[QT_INSTALL_PREFIX]/../Src/qtbase/include
DEPENDPATH += $$PWD/../Dpc

LIBS += -lDpc
unix: LIBS += -lz -ldl

win32 {
    RC_FILE += DConf_mingw.rc
}

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

FORMS += \
    DConf.ui \
    gui/dialogs/frmCreateProj.ui \
    gui/dialogs/frmOpenProj.ui \
    gui/dialogs/ParamDialogBI.ui \
    gui/dialogs/ParamDialogBO.ui \
    gui/forms/interfaces_protocols/RS485/Modbus/master/CommandWidgets/ModbusWidgetCommonCommand.ui \
    gui/forms/interfaces_protocols/RS485/Modbus/master/DeviceCommandLibrary/CmdLibWidget.ui \
    gui/forms/interfaces_protocols/RS485/Modbus/master/ModbusFunctionWidgets/IModbusWidgetFunction.ui \
    gui/forms/interfaces_protocols/RS485/Modbus/master/ModbusWidgetChannelsTable.ui \
    gui/forms/interfaces_protocols/RS485/Modbus/master/ModbusWidgetInitCommands.ui \
    gui/forms/interfaces_protocols/RS485/Modbus/master/ModbusWidgetSlaveSettings.ui \
    gui/forms/interfaces_protocols/RS485/Sybus/master/InitializationCommands/InitSybusCommandCopyParam.ui \
    gui/forms/interfaces_protocols/RS485/Sybus/master/InitializationCommands/InitSybusCommandSetParam.ui \
    gui/forms/table_of_bindings/dialogs/IBindDialog.ui

HEADERS += \
    DConf.h \
    data_model/BindMatrixElem.h \
    data_model/dc_alg.h \
    data_model/dc_alg_cfc.h \
    data_model/dc_alg_internal.h \
    data_model/dc_alg_io.h \
    data_model/dc_alg_io_cfc.h \
    data_model/dc_alg_io_internal.h \
    data_model/dc_board.h \
    data_model/dc_conf_item.h \
    data_model/dc_conf_topology.h \
    data_model/dc_controller.h \
    data_model/dc_data_manager.h \
    data_model/dc_matrix_element.h \
    data_model/dc_matrix_element_alg.h \
    data_model/dc_matrix_element_alg_cfc.h \
    data_model/dc_matrix_element_signal.h \
    data_model/dc_matrix_pool.h \
    data_model/dc_pool.h \
    data_model/dc_project_description.h \
    data_model/dc_properties.h \
    data_model/dc_setting.h \
    data_model/dc_settings_pool.h \
    data_model/dc_signal.h \
    data_model/storage_for_controller_params/DcController_v2.h \
    data_model/storage_for_controller_params/DcParamCfgPool_v2.h \
    data_model/storage_for_controller_params/DcParamCfg_v2.h \
    data_model/storage_for_controller_params/DcParamCfg_v2_Headline.h \
    data_model/storage_for_controller_params/cfg_param_attributes.h \
    data_model/storage_for_controller_params/dc_param.h \
    data_model/storage_for_controller_params/dc_param_cfg.h \
    data_model/storage_for_controller_params/dc_param_cfg_board.h \
    data_model/storage_for_controller_params/dc_param_cfg_pool.h \
    db/dc_db_manager.h \
    db/dc_db_wrapper.h \
    db/sqlite/sqlite3.h \
    db/sqlite/sqlite3ext.h \
    dc_proj_model.h \
    device_operations/DcFormatDriveOperation.h \
    device_operations/DcIDeviceOperation.h \
    device_operations/DcInfoOperation.h \
    device_operations/DcPassportOperation.h \
    device_operations/DcReadConfigOperation.h \
    device_operations/DcResetOperation.h \
    device_operations/DcRestartOperation.h \
    device_operations/DcTemporaryConfigOperation.h \
    device_operations/DcTimeSetOperation.h \
    device_operations/DcWriteConfigOperation.h \
    file_managers/DcAnalogsConversionFileManager.h \
    file_managers/DcFlexLogicFileManager.h \
    file_managers/DcIec61850FileManager.h \
    file_managers/DcModbusMasterSlavesFileManager.h \
    file_managers/DcSpodesMasterSlavesFileManager.h \
    file_managers/IFileManager.h \
    file_managers/IRs485SlaveFileManager.h \
    gui/dialogs/add_controller.h \
    gui/dialogs/binding_dialog.h \
    gui/dialogs/config_deprotec.h \
    gui/dialogs/frmCreateProj.h \
    gui/dialogs/frmOpenProj.h \
    gui/dialogs/title_dialog.h \
    gui/editors/EditorsManager.h \
    gui/editors/types/CheckParamEditor.h \
    gui/editors/types/LineParamEditor.h \
    gui/editors/types/ListEditorContainer.h \
    gui/editors/types/ListParamEditor.h \
    gui/editors/types/ParamEditor.h \
    gui/forms/DcForm.h \
    gui/forms/DcFormFactory.h \
    gui/forms/DcMenu.h \
    gui/forms/DcSignalManager.h \
    gui/forms/algorithms/custom/cfc_editor/cfc_basic_link.h \
    gui/forms/algorithms/custom/cfc_editor/cfc_basic_node.h \
    gui/forms/algorithms/custom/cfc_editor/cfc_basic_scene.h \
    gui/forms/algorithms/custom/cfc_editor/cfc_input_socket.h \
    gui/forms/algorithms/custom/cfc_editor/cfc_line.h \
    gui/forms/algorithms/custom/cfc_editor/cfc_link.h \
    gui/forms/algorithms/custom/cfc_editor/cfc_new_link.h \
    gui/forms/algorithms/custom/cfc_editor/cfc_node.h \
    gui/forms/algorithms/custom/cfc_editor/cfc_output_socket.h \
    gui/forms/algorithms/custom/cfc_editor/cfc_scene.h \
    gui/forms/algorithms/custom/cfc_editor/cfc_socket.h \
    gui/forms/algorithms/custom/cfc_editor/cfc_title.h \
    gui/forms/algorithms/custom/cfc_nodes/cfc_and.h \
    gui/forms/algorithms/custom/cfc_nodes/cfc_bi.h \
    gui/forms/algorithms/custom/cfc_nodes/cfc_bo.h \
    gui/forms/algorithms/custom/cfc_nodes/cfc_generator.h \
    gui/forms/algorithms/custom/cfc_nodes/cfc_impulse_pf.h \
    gui/forms/algorithms/custom/cfc_nodes/cfc_impulse_zf.h \
    gui/forms/algorithms/custom/cfc_nodes/cfc_nodes_list.h \
    gui/forms/algorithms/custom/cfc_nodes/cfc_not.h \
    gui/forms/algorithms/custom/cfc_nodes/cfc_or.h \
    gui/forms/algorithms/custom/cfc_nodes/cfc_return_delay.h \
    gui/forms/algorithms/custom/cfc_nodes/cfc_rs_trigger.h \
    gui/forms/algorithms/custom/cfc_nodes/cfc_trigger_delay.h \
    gui/forms/algorithms/custom/cfc_nodes/cfc_xor.h \
    gui/forms/algorithms/custom/cfc_tools/cfc_editor_item.h \
    gui/forms/algorithms/custom/cfc_tools/cfc_editor_model.h \
    gui/forms/algorithms/custom/cfc_tools/cfc_parser.h \
    gui/forms/algorithms/custom/cfc_tools/byte_code.h \
    gui/forms/algorithms/custom/cfc_tools/cfc_compiler.h \
    gui/forms/algorithms/custom/DcCustomAlgorithmsForm.h \
    gui/forms/algorithms/embedded/AlgDataModel.h \
    gui/forms/algorithms/embedded/DcAlgDefines.h \
    gui/forms/algorithms/embedded/DcEmbeddedAlgorithmsForm.h \
    gui/forms/algorithms/embedded/IAlgorithm.h \
    gui/forms/algorithms/embedded/ProfileWidget.h \
    gui/forms/algorithms/embedded/algs/3Uo/3UoAlgorithm.h \
    gui/forms/algorithms/embedded/algs/ACHR/ACHRAlgorithm.h \
    gui/forms/algorithms/embedded/algs/AMTZ/AMTZAlgorithm.h \
    gui/forms/algorithms/embedded/algs/APV/APVAlgorithm.h \
    gui/forms/algorithms/embedded/algs/AUV/AUVAlgorithm.h \
    gui/forms/algorithms/embedded/algs/AVR/AVRAlgorithm.h \
    gui/forms/algorithms/embedded/algs/AutoKvit/AutoKvit.h \
    gui/forms/algorithms/embedded/algs/BKI/BKIAlgorithm.h \
    gui/forms/algorithms/embedded/algs/Board_Algorithm.h \
    gui/forms/algorithms/embedded/algs/DTO/DTOAlgorithm.h \
    gui/forms/algorithms/embedded/algs/DZT/DZTAlgorithm.h \
    gui/forms/algorithms/embedded/algs/DevicePSC/AMTZ/AMTZ_PSCAlgorithm.h \
    gui/forms/algorithms/embedded/algs/DevicePSC/BasePSCAlgorithm.h \
    gui/forms/algorithms/embedded/algs/DevicePSC/MTZ/MTZ_PSCAlgorithm.h \
    gui/forms/algorithms/embedded/algs/DevicePSC/OZZ/OZZ_PSCAlgorithm.h \
    gui/forms/algorithms/embedded/algs/I2/I2Algorithm.h \
    gui/forms/algorithms/embedded/algs/KCT/KCTAlgorithm.h \
    gui/forms/algorithms/embedded/algs/LZSH/LZSHAlgorithm.h \
    gui/forms/algorithms/embedded/algs/MTZ/MTZAlgorithm.h \
    gui/forms/algorithms/embedded/algs/MTZ_3Io/MTZ_3IoAlgorithm.h \
    gui/forms/algorithms/embedded/algs/MTZ_Accelerated/MTZ_AcceleratedAlgorithm.h \
    gui/forms/algorithms/embedded/algs/MTZ_VN/MTZ_VNAlgorithm.h \
    gui/forms/algorithms/embedded/algs/OZZ_HH/OZZ_HH_Algorithm.h \
    gui/forms/algorithms/embedded/algs/OZZ_Po/OZZ_PoAlgorithm.h \
    gui/forms/algorithms/embedded/algs/SectionVoltage/SectionVoltageAlgorithm.h \
    gui/forms/algorithms/embedded/algs/TO_VN/TO_VNAlgorithm.h \
    gui/forms/algorithms/embedded/algs/U2/U2Algorithm.h \
    gui/forms/algorithms/embedded/algs/UROV/UROVAlgorithm.h \
    gui/forms/algorithms/embedded/algs/VNR/VNRAlgorithm.h \
    gui/forms/algorithms/embedded/algs/VNR/VNR_GSMAlgorithm.h \
    gui/forms/algorithms/embedded/algs/ZMN/ZMNAlgorithm.h \
    gui/forms/algorithms/embedded/algs/ZPN/ZPNAlgorithm.h \
    gui/forms/converter/DcConverterForm.h \
    gui/forms/default/DcDefaultForm.h \
    gui/forms/functions/analogs/DcAnalogsForm.h \
    gui/forms/functions/analogs/comparison/ComparisonModel.h \
    gui/forms/functions/analogs/conversion/ConversionModel.h \
    gui/forms/functions/analogs/conversion/CustomConversionDialog.h \
    gui/forms/functions/analogs/conversion/ICustomConversionSettingsWidget.h \
    gui/forms/functions/analogs/conversion/LinearPiecewiseSettingsWidget.h \
    gui/forms/functions/analogs/conversion/LinearSettingsWidget.h \
    gui/forms/functions/auv_urov/DcAuvUrovForm.h \
    gui/forms/functions/counters/DcCountersForm.h \
    gui/forms/functions/oscillography/DcOscillographyForm.h \
    gui/forms/functions/switches/DcSwitchesForm.h \
    gui/forms/functions/virtual_functions/DcVirtualFunctionsForm.h \
    gui/forms/input_output/analog_inputs/DcAnalogChannelsSettings.h \
    gui/forms/input_output/inputs/DcDiscreteInputACDSignalForm.h \
    gui/forms/input_output/inputs/DcDiscreteInputTwoPositionedSignalsForm.h \
    gui/forms/input_output/outputs/DcDiscreteOutputBlockControl.h \
    gui/forms/input_output/outputs/DcDiscreteOutputChannelForm.h \
    gui/forms/input_output/outputs/DcDiscreteOutputClonesForm.h \
    gui/forms/interfaces_protocols/ConnectionDiscretWidget.h \
    gui/forms/interfaces_protocols/IEC-101/DcIEC101ChannelsForm.h \
    gui/forms/interfaces_protocols/IEC-101/DcIEC101SettingsForm.h \
    gui/forms/interfaces_protocols/IEC-103/DcIEC103ChannelsForm.h \
    gui/forms/interfaces_protocols/IEC-103/DcIEC103SettingsForm.h \
    gui/forms/interfaces_protocols/IEC-61850/61850_defines.h \
    gui/forms/interfaces_protocols/IEC-61850/Communication.h \
    gui/forms/interfaces_protocols/IEC-61850/DataTypeTemplates.h \
    gui/forms/interfaces_protocols/IEC-61850/Dc61850Form.h \
    gui/forms/interfaces_protocols/IEC-61850/GoosePublisher.h \
    gui/forms/interfaces_protocols/IEC-61850/GoosePublishersDialog.h \
    gui/forms/interfaces_protocols/IEC-61850/GseTableModel.h \
    gui/forms/interfaces_protocols/IEC-61850/IEC61850Configuration.h \
    gui/forms/interfaces_protocols/IEC-61850/IED.h \
    gui/forms/interfaces_protocols/IEC-61850/InputGooseWidget.h \
    gui/forms/interfaces_protocols/IEC-61850/SvTableModel.h \
    gui/forms/interfaces_protocols/IEC-61850/TreeItems.h \
    gui/forms/interfaces_protocols/IEC-61850/TreeViewDataModel.h \
    gui/forms/interfaces_protocols/IEC-61850/XMLNode.h \
    gui/forms/interfaces_protocols/RS485/DcRs485BaseProtocol.h \
    gui/forms/interfaces_protocols/RS485/DcRs485Defines.h \
    gui/forms/interfaces_protocols/RS485/DcRs485Form.h \
    gui/forms/interfaces_protocols/RS485/DcRs485PortWidget.h \
    gui/forms/interfaces_protocols/RS485/IEC/101/DcRs485Iec101Protocol.h \
    gui/forms/interfaces_protocols/RS485/IEC/101/slave/DcRs485Iec101SlaveProtocol.h \
    gui/forms/interfaces_protocols/RS485/IEC/103/DcRs485Iec103Protocol.h \
    gui/forms/interfaces_protocols/RS485/IEC/103/slave/DcRs485Iec103SlaveProtocol.h \
    gui/forms/interfaces_protocols/RS485/IEC/DcRs485IecProtocol.h \
    gui/forms/interfaces_protocols/RS485/Modbus/DcRs485ModbusProtocol.h \
    gui/forms/interfaces_protocols/RS485/Modbus/master/CommandNamesJSONSaver.h \
    gui/forms/interfaces_protocols/RS485/Modbus/master/CommandWidgets/ModbusWidgetCommandAins.h \
    gui/forms/interfaces_protocols/RS485/Modbus/master/CommandWidgets/ModbusWidgetCommandCins.h \
    gui/forms/interfaces_protocols/RS485/Modbus/master/CommandWidgets/ModbusWidgetCommandDins.h \
    gui/forms/interfaces_protocols/RS485/Modbus/master/CommandWidgets/ModbusWidgetCommonCommand.h \
    gui/forms/interfaces_protocols/RS485/Modbus/master/Commands/ModbusCommandAins.h \
    gui/forms/interfaces_protocols/RS485/Modbus/master/Commands/ModbusCommandCins.h \
    gui/forms/interfaces_protocols/RS485/Modbus/master/Commands/ModbusCommandDescription.h \
    gui/forms/interfaces_protocols/RS485/Modbus/master/Commands/ModbusCommandDins.h \
    gui/forms/interfaces_protocols/RS485/Modbus/master/Commands/ModbusCommandInitialization.h \
    gui/forms/interfaces_protocols/RS485/Modbus/master/Common/common_CommandDefines.h \
    gui/forms/interfaces_protocols/RS485/Modbus/master/Common/common_CommandWidgetHeaders.h \
    gui/forms/interfaces_protocols/RS485/Modbus/master/Common/common_ExtraFunctions.h \
    gui/forms/interfaces_protocols/RS485/Modbus/master/Common/common_FunctionWidgetHeaders.h \
    gui/forms/interfaces_protocols/RS485/Modbus/master/Common/common_ModbusCommandDefines.h \
    gui/forms/interfaces_protocols/RS485/Modbus/master/Common/common_ModbusCommandsHeaders.h \
    gui/forms/interfaces_protocols/RS485/Modbus/master/Common/common_ModbusFunctionDefines.h \
    gui/forms/interfaces_protocols/RS485/Modbus/master/Common/common_ModbusFunctionsHeaders.h \
    gui/forms/interfaces_protocols/RS485/Modbus/master/DcRs485ModbusMasterProtocol.h \
    gui/forms/interfaces_protocols/RS485/Modbus/master/DeviceCommandLibrary/CmdLibTreeItem.h \
    gui/forms/interfaces_protocols/RS485/Modbus/master/DeviceCommandLibrary/CmdLibWidget.h \
    gui/forms/interfaces_protocols/RS485/Modbus/master/DeviceCommandLibrary/CommandLibraryModel.h \
    gui/forms/interfaces_protocols/RS485/Modbus/master/ModbusDialogSlaveInit_readOrCreate.h \
    gui/forms/interfaces_protocols/RS485/Modbus/master/ModbusDialogSlaveInit_standartOrNot.h \
    gui/forms/interfaces_protocols/RS485/Modbus/master/ModbusFunctionWidgets/IModbusWidgetFunction.h \
    gui/forms/interfaces_protocols/RS485/Modbus/master/ModbusFunctionWidgets/ModbusWidgetFunction02_ReadDiscreteInputs.h \
    gui/forms/interfaces_protocols/RS485/Modbus/master/ModbusFunctionWidgets/ModbusWidgetFunction04_ReadInputRegisters.h \
    gui/forms/interfaces_protocols/RS485/Modbus/master/ModbusFunctionWidgets/ModbusWidgetFunction_Custom.h \
    gui/forms/interfaces_protocols/RS485/Modbus/master/ModbusFunctions/ModbusFunction.h \
    gui/forms/interfaces_protocols/RS485/Modbus/master/ModbusFunctions/ModbusFunction02_ReadDiscreteInputs.h \
    gui/forms/interfaces_protocols/RS485/Modbus/master/ModbusFunctions/ModbusFunction04_ReadInputRegisters.h \
    gui/forms/interfaces_protocols/RS485/Modbus/master/ModbusFunctions/ModbusFunctionCustom.h \
    gui/forms/interfaces_protocols/RS485/Modbus/master/ModbusParser.h \
    gui/forms/interfaces_protocols/RS485/Modbus/master/ModbusSlaveDefinition.h \
    gui/forms/interfaces_protocols/RS485/Modbus/master/ModbusSlaveFileSaver.h \
    gui/forms/interfaces_protocols/RS485/Modbus/master/ModbusWidgetChannelsTable.h \
    gui/forms/interfaces_protocols/RS485/Modbus/master/ModbusWidgetInitCommands.h \
    gui/forms/interfaces_protocols/RS485/Modbus/master/ModbusWidgetSlaveSettings.h \
    gui/forms/interfaces_protocols/RS485/Modbus/slave/DcRs485ModbusSlaveProtocol.h \
    gui/forms/interfaces_protocols/RS485/PortInfo.h \
    gui/forms/interfaces_protocols/RS485/Spodes/DcRs485SpodesProtocol.h \
    gui/forms/interfaces_protocols/RS485/Spodes/master/DcRs485SpodesMasterProtocol.h \
    gui/forms/interfaces_protocols/RS485/Spodes/master/SpodesMasterCommon.h \
    gui/forms/interfaces_protocols/RS485/Spodes/master/SpodesSlaveSettingsDialog.h \
    gui/forms/interfaces_protocols/RS485/Spodes/master/SpodesSlaveWidget.h \
    gui/forms/interfaces_protocols/RS485/Spodes/slave/DcRs485SpodesSlaveProtocol.h \
    gui/forms/interfaces_protocols/RS485/Sybus/DcRs485SybusProtocol.h \
    gui/forms/interfaces_protocols/RS485/Sybus/master/DcRs485SybusMasterProtocol.h \
    gui/forms/interfaces_protocols/RS485/Sybus/master/InitializationCommands/EditorInitCommands.h \
    gui/forms/interfaces_protocols/RS485/Sybus/master/InitializationCommands/InitSybusCommandCopyParam.h \
    gui/forms/interfaces_protocols/RS485/Sybus/master/InitializationCommands/InitSybusCommandSetParam.h \
    gui/forms/interfaces_protocols/RS485/Sybus/master/InitializationCommands/InterfaseInitCommand.h \
    gui/forms/interfaces_protocols/RS485/Sybus/master/InitializationCommands/TabSybusInitialization.h \
    gui/forms/interfaces_protocols/RS485/Sybus/master/InitializationCommands/init_commands_defines.h \
    gui/forms/interfaces_protocols/RS485/Sybus/master/TabSybusMasterChannels.h \
    gui/forms/interfaces_protocols/RS485/Sybus/master/TabSybusMasterIdentification.h \
    gui/forms/interfaces_protocols/RS485/Sybus/master/definesSlaveMode.h \
    gui/forms/interfaces_protocols/RS485/Sybus/slave/DcRs485SybusSlaveProtocol.h \
    gui/forms/interfaces_protocols/RS485/common_slave_functions.h \
    gui/forms/interfaces_protocols/RS485/macrosCheckPointer.h \
    gui/forms/interfaces_protocols/SIM/DcSimForm.h \
    gui/forms/interfaces_protocols/SPODES/DcSpodesChannelsForm.h \
    gui/forms/interfaces_protocols/SPODES/DcSpodesSettingsForm.h \
    gui/forms/interfaces_protocols/TCP/DcTcpForm.h \
    gui/forms/interfaces_protocols/TimeSync/DcTimeSyncForm.h \
    gui/forms/main/DateTimeWidget.h \
    gui/forms/main/DcMainForm.h \
    gui/forms/main/DcPassportDialog.h \
    gui/forms/main/DeviceWidget.h \
    gui/forms/main/IDeviceTabWidget.h \
    gui/forms/settings/DcSettingsForm.h \
    gui/forms/table_of_bindings/algs_delegate.h \
    gui/forms/table_of_bindings/dialogs/AlgBindDialog.h \
    gui/forms/table_of_bindings/dialogs/IBindDialog.h \
    gui/forms/table_of_bindings/dialogs/InputBindDialog.h \
    gui/forms/table_of_bindings/dialogs/OutputBindDialog.h \
    gui/forms/table_of_bindings/dialogs/delegates/AlgMatrixDelegate.h \
    gui/forms/table_of_bindings/dialogs/delegates/IMatrixDelegate.h \
    gui/forms/table_of_bindings/dialogs/delegates/InputMatrixDelegate.h \
    gui/forms/table_of_bindings/dialogs/delegates/OutputMatrixDelegate.h \
    gui/forms/table_of_bindings/dialogs/models/AlgBindDlgModel.h \
    gui/forms/table_of_bindings/dialogs/models/IDlgModel.h \
    gui/forms/table_of_bindings/dialogs/models/InputBindDlgModel.h \
    gui/forms/table_of_bindings/dialogs/models/OutputBindDlgModel.h \
    gui/forms/table_of_bindings/dialogs/signal_names_functions.h \
    gui/forms/table_of_bindings/bindings_form.h \
    gui/forms/table_of_bindings/outputs_delegate.h \
    gui/forms/thresholds_settings/DcPqiEventSettingsForm.h \
    gui/forms/thresholds_settings/DcPqiSettingsForm.h \
    gui/forms/thresholds_settings/DcThresholdsForm.h \
    journal/JSource.h \
    report/DcIConfigReport.h \
    report/DcReportTable.h \
    report/DcTextDocumentConfigReport.h \
    service_manager/service_manager.h \
    service_manager/services/alg/alg_service.h \
    service_manager/services/alg/alg_service_input.h \
    service_manager/services/alg/alg_service_output.h \
    service_manager/services/alg_cfc/cfc_alg_service.h \
    service_manager/services/alg_cfc/cfc_service_input.h \
    service_manager/services/alg_cfc/cfc_service_output.h \
    service_manager/services/func/func_service.h \
    service_manager/services/func/func_service_output.h \
    service_manager/services/func/vfunc.h \
    service_manager/services/service.h \
    service_manager/services/service_input.h \
    service_manager/services/service_io.h \
    service_manager/services/service_output.h \
    service_manager/signals/ain_signal.h \
    service_manager/signals/ain_virtual.h \
    service_manager/signals/cin_signal.h \
    service_manager/signals/cin_virtual.h \
    service_manager/signals/din_adc.h \
    service_manager/signals/din_logical.h \
    service_manager/signals/din_physical.h \
    service_manager/signals/din_remote.h \
    service_manager/signals/din_signal.h \
    service_manager/signals/din_virtual.h \
    service_manager/signals/dout_signal.h \
    service_manager/signals/dout_virtual.h \
    service_manager/signals/input_signal.h \
    service_manager/signals/output_signal.h \
    service_manager/signals/signal.h \
    service_manager/signals/target_element.h \
    service_manager/signals/virtual_input_signal.h \
    service_manager/signals/virtual_output_signal.h \
    updater/updater.h \
    utils/bindings_update.h \
    utils/cfg_path.h \
    utils/qzipreader_p.h \
    utils/qzipwriter_p.h \
    utils/rapidxml.hpp \
    utils/rapidxml_print.hpp \
    version.h \
    gui/dialogs/ParamDialogBI.h \
    gui/dialogs/ParamDialogBO.h \
    gui/dialogs/info_list_dialog.h \
    gui/dialogs/params_dialog.h \
    gui/dialogs/scene_dialog.h \
    gui/forms/algorithms/custom/Editor/dummy_link.h \
    gui/forms/algorithms/custom/Editor/editor_link.h \
    gui/forms/algorithms/custom/Editor/editor_link_data.h \
    gui/forms/algorithms/custom/Editor/editor_node.h \
    gui/forms/algorithms/custom/Editor/editor_node_data.h \
    gui/forms/algorithms/custom/Editor/editor_scene.h \
    gui/forms/algorithms/custom/Editor/editor_socket.h \
    gui/forms/algorithms/custom/Editor/editor_socket_data.h \
    gui/forms/algorithms/custom/Editor/graphic_line.h \
    gui/forms/algorithms/custom/Editor/graphic_path.h \
    gui/forms/algorithms/custom/Editor/title_item.h \
    gui/forms/algorithms/custom/Nodes/and_node.h \
    gui/forms/algorithms/custom/Nodes/bi_node.h \
    gui/forms/algorithms/custom/Nodes/bo_node.h \
    gui/forms/algorithms/custom/Nodes/generator_node.h \
    gui/forms/algorithms/custom/Nodes/impulse_pf_node.h \
    gui/forms/algorithms/custom/Nodes/impulse_zf_node.h \
    gui/forms/algorithms/custom/Nodes/not_node.h \
    gui/forms/algorithms/custom/Nodes/or_node.h \
    gui/forms/algorithms/custom/Nodes/return_delay_node.h \
    gui/forms/algorithms/custom/Nodes/rs_trigger_node.h \
    gui/forms/algorithms/custom/Nodes/trigger_delay_node.h \
    gui/forms/algorithms/custom/Nodes/xor_node.h \
    gui/forms/algorithms/custom/dep_parser.h \
    gui/forms/algorithms/custom/flex_editor_form.h \
    gui/forms/algorithms/custom/flexlogic_namespace.h \
    gui/forms/main/filesystem_page.h \
    gui/forms/input_output/inputs/dins_board_widget.h \
    gui/forms/input_output/inputs/dins_external_form.h \
    gui/forms/input_output/inputs/dins_logical_form.h \
    gui/forms/input_output/inputs/dins_model.h \
    gui/forms/input_output/inputs/dins_physical_form.h \
    gui/forms/input_output/inputs/dins_virtual_form.h \
    gui/forms/algorithms/embedded/algs/MTZ_NN/MTZ_NN_Algorithm.h \
    gui/forms/algorithms/embedded/algs/MTZ_SN/MTZ_SN_Algorithm.h \
    device_operations/DcUpdateDeviceOperation.h \
    gui/forms/thresholds_settings/pqi_event_model.h \
    gui/forms/functions/oscillography/AnalogsModel.h \
    gui/forms/interfaces_protocols/RS485/TransparentChannel/dc_rs485_transparent_protocol.h

SOURCES += \
    DConf.cpp \
    data_model/dc_alg.cpp \
    data_model/dc_alg_cfc.cpp \
    data_model/dc_alg_internal.cpp \
    data_model/dc_alg_io_cfc.cpp \
    data_model/dc_alg_io_internal.cpp \
    data_model/dc_board.cpp \
    data_model/dc_conf_item.cpp \
    data_model/dc_conf_topology.cpp \
    data_model/dc_controller.cpp \
    data_model/dc_data_manager.cpp \
    data_model/dc_matrix_element.cpp \
    data_model/dc_matrix_element_alg.cpp \
    data_model/dc_matrix_element_alg_cfc.cpp \
    data_model/dc_matrix_element_signal.cpp \
    data_model/dc_project_description.cpp \
    data_model/dc_properties.cpp \
    data_model/dc_setting.cpp \
    data_model/dc_settings_pool.cpp \
    data_model/dc_signal.cpp \
    data_model/storage_for_controller_params/DcController_v2.cpp \
    data_model/storage_for_controller_params/DcParamCfgPool_v2.cpp \
    data_model/storage_for_controller_params/DcParamCfg_v2.cpp \
    data_model/storage_for_controller_params/DcParamCfg_v2_Headline.cpp \
    data_model/storage_for_controller_params/cfg_param_attributes.cpp \
    data_model/storage_for_controller_params/dc_param.cpp \
    data_model/storage_for_controller_params/dc_param_cfg.cpp \
    data_model/storage_for_controller_params/dc_param_cfg_board.cpp \
    db/dc_db_manager.cpp \
    db/dc_db_wrapper.cpp \
    db/sqlite/sqlite3.c \
    dc_proj_model.cpp \
    device_operations/DcFormatDriveOperation.cpp \
    device_operations/DcIDeviceOperation.cpp \
    device_operations/DcInfoOperation.cpp \
    device_operations/DcPassportOperation.cpp \
    device_operations/DcReadConfigOperation.cpp \
    device_operations/DcResetOperation.cpp \
    device_operations/DcRestartOperation.cpp \
    device_operations/DcTemporaryConfigOperation.cpp \
    device_operations/DcTimeSetOperation.cpp \
    device_operations/DcWriteConfigOperation.cpp \
    file_managers/DcAnalogsConversionFileManager.cpp \
    file_managers/DcFlexLogicFileManager.cpp \
    file_managers/DcIec61850FileManager.cpp \
    file_managers/DcModbusMasterSlavesFileManager.cpp \
    file_managers/DcSpodesMasterSlavesFileManager.cpp \
    file_managers/IFileManager.cpp \
    file_managers/IRs485SlaveFileManager.cpp \
    gui/dialogs/add_controller.cpp \
    gui/dialogs/binding_dialog.cpp \
    gui/dialogs/config_deprotec.cpp \
    gui/dialogs/frmCreateProj.cpp \
    gui/dialogs/frmOpenProj.cpp \
    gui/dialogs/title_dialog.cpp \
    gui/editors/EditorsManager.cpp \
    gui/editors/types/CheckParamEditor.cpp \
    gui/editors/types/LineParamEditor.cpp \
    gui/editors/types/ListEditorContainer.cpp \
    gui/editors/types/ListParamEditor.cpp \
    gui/editors/types/ParamEditor.cpp \
    gui/forms/DcForm.cpp \
    gui/forms/DcFormFactory.cpp \
    gui/forms/DcMenu.cpp \
    gui/forms/DcSignalManager.cpp \
    gui/forms/algorithms/custom/cfc_editor/cfc_basic_link.cpp \
    gui/forms/algorithms/custom/cfc_editor/cfc_basic_node.cpp \
    gui/forms/algorithms/custom/cfc_editor/cfc_basic_scene.cpp \
    gui/forms/algorithms/custom/cfc_editor/cfc_input_socket.cpp \
    gui/forms/algorithms/custom/cfc_editor/cfc_line.cpp \
    gui/forms/algorithms/custom/cfc_editor/cfc_link.cpp \
    gui/forms/algorithms/custom/cfc_editor/cfc_new_link.cpp \
    gui/forms/algorithms/custom/cfc_editor/cfc_node.cpp \
    gui/forms/algorithms/custom/cfc_editor/cfc_output_socket.cpp \
    gui/forms/algorithms/custom/cfc_editor/cfc_scene.cpp \
    gui/forms/algorithms/custom/cfc_editor/cfc_socket.cpp \
    gui/forms/algorithms/custom/cfc_editor/cfc_title.cpp \
    gui/forms/algorithms/custom/cfc_nodes/cfc_and.cpp \
    gui/forms/algorithms/custom/cfc_nodes/cfc_bi.cpp \
    gui/forms/algorithms/custom/cfc_nodes/cfc_bo.cpp \
    gui/forms/algorithms/custom/cfc_nodes/cfc_generator.cpp \
    gui/forms/algorithms/custom/cfc_nodes/cfc_impulse_pf.cpp \
    gui/forms/algorithms/custom/cfc_nodes/cfc_impulse_zf.cpp \
    gui/forms/algorithms/custom/cfc_nodes/cfc_not.cpp \
    gui/forms/algorithms/custom/cfc_nodes/cfc_or.cpp \
    gui/forms/algorithms/custom/cfc_nodes/cfc_return_delay.cpp \
    gui/forms/algorithms/custom/cfc_nodes/cfc_rs_trigger.cpp \
    gui/forms/algorithms/custom/cfc_nodes/cfc_trigger_delay.cpp \
    gui/forms/algorithms/custom/cfc_nodes/cfc_xor.cpp \
    gui/forms/algorithms/custom/cfc_tools/cfc_editor_item.cpp \
    gui/forms/algorithms/custom/cfc_tools/cfc_editor_model.cpp \
    gui/forms/algorithms/custom/cfc_tools/cfc_parser.cpp \
    gui/forms/algorithms/custom/cfc_tools/byte_code.cpp \
    gui/forms/algorithms/custom/cfc_tools/cfc_compiler.cpp \
    gui/forms/algorithms/custom/DcCustomAlgorithmsForm.cpp \
    gui/forms/algorithms/embedded/AlgDataModel.cpp \
    gui/forms/algorithms/embedded/DcEmbeddedAlgorithmsForm.cpp \
    gui/forms/algorithms/embedded/IAlgorithm.cpp \
    gui/forms/algorithms/embedded/ProfileWidget.cpp \
    gui/forms/algorithms/embedded/algs/3Uo/3UoAlgorithm.cpp \
    gui/forms/algorithms/embedded/algs/ACHR/ACHRAlgorithm.cpp \
    gui/forms/algorithms/embedded/algs/AMTZ/AMTZAlgorithm.cpp \
    gui/forms/algorithms/embedded/algs/APV/APVAlgorithm.cpp \
    gui/forms/algorithms/embedded/algs/AUV/AUVAlgorithm.cpp \
    gui/forms/algorithms/embedded/algs/AVR/AVRAlgorithm.cpp \
    gui/forms/algorithms/embedded/algs/AutoKvit/AutoKvit.cpp \
    gui/forms/algorithms/embedded/algs/BKI/BKIAlgorithm.cpp \
    gui/forms/algorithms/embedded/algs/Board_Algorithm.cpp \
    gui/forms/algorithms/embedded/algs/DTO/DTOAlgorithm.cpp \
    gui/forms/algorithms/embedded/algs/DZT/DZTAlgorithm.cpp \
    gui/forms/algorithms/embedded/algs/DevicePSC/AMTZ/AMTZ_PSCAlgorithm.cpp \
    gui/forms/algorithms/embedded/algs/DevicePSC/BasePSCAlgorithm.cpp \
    gui/forms/algorithms/embedded/algs/DevicePSC/MTZ/MTZ_PSCAlgorithm.cpp \
    gui/forms/algorithms/embedded/algs/DevicePSC/OZZ/OZZ_PSCAlgorithm.cpp \
    gui/forms/algorithms/embedded/algs/I2/I2Algorithm.cpp \
    gui/forms/algorithms/embedded/algs/KCT/KCTAlgorithm.cpp \
    gui/forms/algorithms/embedded/algs/LZSH/LZSHAlgorithm.cpp \
    gui/forms/algorithms/embedded/algs/MTZ/MTZAlgorithm.cpp \
    gui/forms/algorithms/embedded/algs/MTZ_3Io/MTZ_3IoAlgorithm.cpp \
    gui/forms/algorithms/embedded/algs/MTZ_Accelerated/MTZ_AcceleratedAlgorithm.cpp \
    gui/forms/algorithms/embedded/algs/MTZ_VN/MTZ_VNAlgorithm.cpp \
    gui/forms/algorithms/embedded/algs/OZZ_HH/OZZ_HH_Algorithm.cpp \
    gui/forms/algorithms/embedded/algs/OZZ_Po/OZZ_PoAlgorithm.cpp \
    gui/forms/algorithms/embedded/algs/SectionVoltage/SectionVoltageAlgorithm.cpp \
    gui/forms/algorithms/embedded/algs/TO_VN/TO_VNAlgorithm.cpp \
    gui/forms/algorithms/embedded/algs/U2/U2Algorithm.cpp \
    gui/forms/algorithms/embedded/algs/UROV/UROVAlgorithm.cpp \
    gui/forms/algorithms/embedded/algs/VNR/VNRAlgorithm.cpp \
    gui/forms/algorithms/embedded/algs/VNR/VNR_GSMAlgorithm.cpp \
    gui/forms/algorithms/embedded/algs/ZMN/ZMNAlgorithm.cpp \
    gui/forms/algorithms/embedded/algs/ZPN/ZPNAlgorithm.cpp \
    gui/forms/converter/DcConverterForm.cpp \
    gui/forms/default/DcDefaultForm.cpp \
    gui/forms/functions/analogs/DcAnalogsForm.cpp \
    gui/forms/functions/analogs/comparison/ComparisonModel.cpp \
    gui/forms/functions/analogs/conversion/ConversionModel.cpp \
    gui/forms/functions/analogs/conversion/CustomConversionDialog.cpp \
    gui/forms/functions/analogs/conversion/LinearPiecewiseSettingsWidget.cpp \
    gui/forms/functions/analogs/conversion/LinearSettingsWidget.cpp \
    gui/forms/functions/auv_urov/DcAuvUrovForm.cpp \
    gui/forms/functions/counters/DcCountersForm.cpp \
    gui/forms/functions/oscillography/DcOscillographyForm.cpp \
    gui/forms/functions/switches/DcSwitchesForm.cpp \
    gui/forms/functions/virtual_functions/DcVirtualFunctionsForm.cpp \
    gui/forms/input_output/analog_inputs/DcAnalogChannelsSettings.cpp \
    gui/forms/input_output/inputs/DcDiscreteInputACDSignalForm.cpp \
    gui/forms/input_output/inputs/DcDiscreteInputTwoPositionedSignalsForm.cpp \
    gui/forms/input_output/outputs/DcDiscreteOutputBlockControl.cpp \
    gui/forms/input_output/outputs/DcDiscreteOutputChannelForm.cpp \
    gui/forms/input_output/outputs/DcDiscreteOutputClonesForm.cpp \
    gui/forms/interfaces_protocols/ConnectionDiscretWidget.cpp \
    gui/forms/interfaces_protocols/IEC-101/DcIEC101ChannelsForm.cpp \
    gui/forms/interfaces_protocols/IEC-101/DcIEC101SettingsForm.cpp \
    gui/forms/interfaces_protocols/IEC-103/DcIEC103ChannelsForm.cpp \
    gui/forms/interfaces_protocols/IEC-103/DcIEC103SettingsForm.cpp \
    gui/forms/interfaces_protocols/IEC-61850/Communication.cpp \
    gui/forms/interfaces_protocols/IEC-61850/DataTypeTemplates.cpp \
    gui/forms/interfaces_protocols/IEC-61850/Dc61850Form.cpp \
    gui/forms/interfaces_protocols/IEC-61850/GoosePublisher.cpp \
    gui/forms/interfaces_protocols/IEC-61850/GoosePublishersDialog.cpp \
    gui/forms/interfaces_protocols/IEC-61850/GseTableModel.cpp \
    gui/forms/interfaces_protocols/IEC-61850/IEC61850Configuration.cpp \
    gui/forms/interfaces_protocols/IEC-61850/IED.cpp \
    gui/forms/interfaces_protocols/IEC-61850/InputGooseWidget.cpp \
    gui/forms/interfaces_protocols/IEC-61850/SvTableModel.cpp \
    gui/forms/interfaces_protocols/IEC-61850/TreeItems.cpp \
    gui/forms/interfaces_protocols/IEC-61850/TreeViewDataModel.cpp \
    gui/forms/interfaces_protocols/IEC-61850/XMLNode.cpp \
    gui/forms/interfaces_protocols/RS485/DcRs485BaseProtocol.cpp \
    gui/forms/interfaces_protocols/RS485/DcRs485Form.cpp \
    gui/forms/interfaces_protocols/RS485/DcRs485PortWidget.cpp \
    gui/forms/interfaces_protocols/RS485/IEC/101/DcRs485Iec101Protocol.cpp \
    gui/forms/interfaces_protocols/RS485/IEC/101/slave/DcRs485Iec101SlaveProtocol.cpp \
    gui/forms/interfaces_protocols/RS485/IEC/103/DcRs485Iec103Protocol.cpp \
    gui/forms/interfaces_protocols/RS485/IEC/103/slave/DcRs485Iec103SlaveProtocol.cpp \
    gui/forms/interfaces_protocols/RS485/IEC/DcRs485IecProtocol.cpp \
    gui/forms/interfaces_protocols/RS485/Modbus/DcRs485ModbusProtocol.cpp \
    gui/forms/interfaces_protocols/RS485/Modbus/master/CommandNamesJSONSaver.cpp \
    gui/forms/interfaces_protocols/RS485/Modbus/master/CommandWidgets/ModbusWidgetCommandAins.cpp \
    gui/forms/interfaces_protocols/RS485/Modbus/master/CommandWidgets/ModbusWidgetCommandCins.cpp \
    gui/forms/interfaces_protocols/RS485/Modbus/master/CommandWidgets/ModbusWidgetCommandDins.cpp \
    gui/forms/interfaces_protocols/RS485/Modbus/master/CommandWidgets/ModbusWidgetCommonCommand.cpp \
    gui/forms/interfaces_protocols/RS485/Modbus/master/Commands/ModbusCommandAins.cpp \
    gui/forms/interfaces_protocols/RS485/Modbus/master/Commands/ModbusCommandCins.cpp \
    gui/forms/interfaces_protocols/RS485/Modbus/master/Commands/ModbusCommandDescription.cpp \
    gui/forms/interfaces_protocols/RS485/Modbus/master/Commands/ModbusCommandDins.cpp \
    gui/forms/interfaces_protocols/RS485/Modbus/master/Commands/ModbusCommandInitialization.cpp \
    gui/forms/interfaces_protocols/RS485/Modbus/master/Common/common_ExtraFunctions.cpp \
    gui/forms/interfaces_protocols/RS485/Modbus/master/DcRs485ModbusMasterProtocol.cpp \
    gui/forms/interfaces_protocols/RS485/Modbus/master/DeviceCommandLibrary/CmdLibTreeItem.cpp \
    gui/forms/interfaces_protocols/RS485/Modbus/master/DeviceCommandLibrary/CmdLibWidget.cpp \
    gui/forms/interfaces_protocols/RS485/Modbus/master/DeviceCommandLibrary/CommandLibraryModel.cpp \
    gui/forms/interfaces_protocols/RS485/Modbus/master/ModbusDialogSlaveInit_readOrCreate.cpp \
    gui/forms/interfaces_protocols/RS485/Modbus/master/ModbusDialogSlaveInit_standartOrNot.cpp \
    gui/forms/interfaces_protocols/RS485/Modbus/master/ModbusFunctionWidgets/IModbusWidgetFunction.cpp \
    gui/forms/interfaces_protocols/RS485/Modbus/master/ModbusFunctionWidgets/ModbusWidgetFunction02_ReadDiscreteInputs.cpp \
    gui/forms/interfaces_protocols/RS485/Modbus/master/ModbusFunctionWidgets/ModbusWidgetFunction04_ReadInputRegisters.cpp \
    gui/forms/interfaces_protocols/RS485/Modbus/master/ModbusFunctionWidgets/ModbusWidgetFunction_Custom.cpp \
    gui/forms/interfaces_protocols/RS485/Modbus/master/ModbusFunctions/ModbusFunction.cpp \
    gui/forms/interfaces_protocols/RS485/Modbus/master/ModbusFunctions/ModbusFunction02_ReadDiscreteInputs.cpp \
    gui/forms/interfaces_protocols/RS485/Modbus/master/ModbusFunctions/ModbusFunction04_ReadInputRegisters.cpp \
    gui/forms/interfaces_protocols/RS485/Modbus/master/ModbusFunctions/ModbusFunctionCustom.cpp \
    gui/forms/interfaces_protocols/RS485/Modbus/master/ModbusParser.cpp \
    gui/forms/interfaces_protocols/RS485/Modbus/master/ModbusSlaveDefinition.cpp \
    gui/forms/interfaces_protocols/RS485/Modbus/master/ModbusSlaveFileSaver.cpp \
    gui/forms/interfaces_protocols/RS485/Modbus/master/ModbusWidgetChannelsTable.cpp \
    gui/forms/interfaces_protocols/RS485/Modbus/master/ModbusWidgetInitCommands.cpp \
    gui/forms/interfaces_protocols/RS485/Modbus/master/ModbusWidgetSlaveSettings.cpp \
    gui/forms/interfaces_protocols/RS485/Modbus/slave/DcRs485ModbusSlaveProtocol.cpp \
    gui/forms/interfaces_protocols/RS485/PortInfo.cpp \
    gui/forms/interfaces_protocols/RS485/Spodes/DcRs485SpodesProtocol.cpp \
    gui/forms/interfaces_protocols/RS485/Spodes/master/DcRs485SpodesMasterProtocol.cpp \
    gui/forms/interfaces_protocols/RS485/Spodes/master/SpodesMasterCommon.cpp \
    gui/forms/interfaces_protocols/RS485/Spodes/master/SpodesSlaveSettingsDialog.cpp \
    gui/forms/interfaces_protocols/RS485/Spodes/master/SpodesSlaveWidget.cpp \
    gui/forms/interfaces_protocols/RS485/Spodes/slave/DcRs485SpodesSlaveProtocol.cpp \
    gui/forms/interfaces_protocols/RS485/Sybus/DcRs485SybusProtocol.cpp \
    gui/forms/interfaces_protocols/RS485/Sybus/master/DcRs485SybusMasterProtocol.cpp \
    gui/forms/interfaces_protocols/RS485/Sybus/master/InitializationCommands/EditorInitCommands.cpp \
    gui/forms/interfaces_protocols/RS485/Sybus/master/InitializationCommands/InitSybusCommandCopyParam.cpp \
    gui/forms/interfaces_protocols/RS485/Sybus/master/InitializationCommands/InitSybusCommandSetParam.cpp \
    gui/forms/interfaces_protocols/RS485/Sybus/master/InitializationCommands/TabSybusInitialization.cpp \
    gui/forms/interfaces_protocols/RS485/Sybus/master/TabSybusMasterChannels.cpp \
    gui/forms/interfaces_protocols/RS485/Sybus/master/TabSybusMasterIdentification.cpp \
    gui/forms/interfaces_protocols/RS485/Sybus/slave/DcRs485SybusSlaveProtocol.cpp \
    gui/forms/interfaces_protocols/RS485/common_slave_functions.cpp \
    gui/forms/interfaces_protocols/SIM/DcSimForm.cpp \
    gui/forms/interfaces_protocols/SPODES/DcSpodesChannelsForm.cpp \
    gui/forms/interfaces_protocols/SPODES/DcSpodesSettingsForm.cpp \
    gui/forms/interfaces_protocols/TCP/DcTcpForm.cpp \
    gui/forms/interfaces_protocols/TimeSync/DcTimeSyncForm.cpp \
    gui/forms/main/DateTimeWidget.cpp \
    gui/forms/main/DcMainForm.cpp \
    gui/forms/main/DcPassportDialog.cpp \
    gui/forms/main/DeviceWidget.cpp \
    gui/forms/main/IDeviceTabWidget.cpp \
    gui/forms/settings/DcSettingsForm.cpp \
    gui/forms/table_of_bindings/algs_delegate.cpp \
    gui/forms/table_of_bindings/dialogs/AlgBindDialog.cpp \
    gui/forms/table_of_bindings/dialogs/IBindDialog.cpp \
    gui/forms/table_of_bindings/dialogs/InputBindDialog.cpp \
    gui/forms/table_of_bindings/dialogs/OutputBindDialog.cpp \
    gui/forms/table_of_bindings/dialogs/delegates/AlgMatrixDelegate.cpp \
    gui/forms/table_of_bindings/dialogs/delegates/IMatrixDelegate.cpp \
    gui/forms/table_of_bindings/dialogs/delegates/InputMatrixDelegate.cpp \
    gui/forms/table_of_bindings/dialogs/delegates/OutputMatrixDelegate.cpp \
    gui/forms/table_of_bindings/dialogs/models/AlgBindDlgModel.cpp \
    gui/forms/table_of_bindings/dialogs/models/IDlgModel.cpp \
    gui/forms/table_of_bindings/dialogs/models/InputBindDlgModel.cpp \
    gui/forms/table_of_bindings/dialogs/models/OutputBindDlgModel.cpp \
    gui/forms/table_of_bindings/dialogs/signal_names_functions.cpp \
    gui/forms/table_of_bindings/bindings_form.cpp \
    gui/forms/table_of_bindings/outputs_delegate.cpp \
    gui/forms/thresholds_settings/DcPqiEventSettingsForm.cpp \
    gui/forms/thresholds_settings/DcPqiSettingsForm.cpp \
    gui/forms/thresholds_settings/DcThresholdsForm.cpp \
    main.cpp \
    report/DcIConfigReport.cpp \
    report/DcReportTable.cpp \
    report/DcTextDocumentConfigReport.cpp \
    service_manager/service_manager.cpp \
    service_manager/services/alg/alg_service.cpp \
    service_manager/services/alg/alg_service_input.cpp \
    service_manager/services/alg/alg_service_output.cpp \
    service_manager/services/alg_cfc/cfc_alg_service.cpp \
    service_manager/services/alg_cfc/cfc_service_input.cpp \
    service_manager/services/alg_cfc/cfc_service_output.cpp \
    service_manager/services/func/func_service.cpp \
    service_manager/services/func/func_service_output.cpp \
    service_manager/services/func/vfunc.cpp \
    service_manager/services/service.cpp \
    service_manager/services/service_input.cpp \
    service_manager/services/service_io.cpp \
    service_manager/services/service_output.cpp \
    service_manager/signals/ain_signal.cpp \
    service_manager/signals/ain_virtual.cpp \
    service_manager/signals/cin_signal.cpp \
    service_manager/signals/cin_virtual.cpp \
    service_manager/signals/din_adc.cpp \
    service_manager/signals/din_logical.cpp \
    service_manager/signals/din_physical.cpp \
    service_manager/signals/din_remote.cpp \
    service_manager/signals/din_signal.cpp \
    service_manager/signals/din_virtual.cpp \
    service_manager/signals/dout_signal.cpp \
    service_manager/signals/dout_virtual.cpp \
    service_manager/signals/input_signal.cpp \
    service_manager/signals/output_signal.cpp \
    service_manager/signals/signal.cpp \
    service_manager/signals/target_element.cpp \
    service_manager/signals/virtual_input_signal.cpp \
    service_manager/signals/virtual_output_signal.cpp \
    updater/updater.cpp \
    utils/bindings_update.cpp \
    utils/cfg_path.cpp \
    utils/qzip.cpp \
    gui/dialogs/ParamDialogBI.cpp \
    gui/dialogs/ParamDialogBO.cpp \
    gui/dialogs/info_list_dialog.cpp \
    gui/dialogs/params_dialog.cpp \
    gui/dialogs/scene_dialog.cpp \
    gui/forms/algorithms/custom/Editor/dummy_link.cpp \
    gui/forms/algorithms/custom/Editor/editor_link.cpp \
    gui/forms/algorithms/custom/Editor/editor_link_data.cpp \
    gui/forms/algorithms/custom/Editor/editor_node.cpp \
    gui/forms/algorithms/custom/Editor/editor_node_data.cpp \
    gui/forms/algorithms/custom/Editor/editor_scene.cpp \
    gui/forms/algorithms/custom/Editor/editor_socket.cpp \
    gui/forms/algorithms/custom/Editor/editor_socket_data.cpp \
    gui/forms/algorithms/custom/Editor/graphic_line.cpp \
    gui/forms/algorithms/custom/Editor/graphic_path.cpp \
    gui/forms/algorithms/custom/Editor/title_item.cpp \
    gui/forms/algorithms/custom/Nodes/and_node.cpp \
    gui/forms/algorithms/custom/Nodes/bi_node.cpp \
    gui/forms/algorithms/custom/Nodes/bo_node.cpp \
    gui/forms/algorithms/custom/Nodes/generator_node.cpp \
    gui/forms/algorithms/custom/Nodes/impulse_pf_node.cpp \
    gui/forms/algorithms/custom/Nodes/impulse_zf_node.cpp \
    gui/forms/algorithms/custom/Nodes/not_node.cpp \
    gui/forms/algorithms/custom/Nodes/or_node.cpp \
    gui/forms/algorithms/custom/Nodes/return_delay_node.cpp \
    gui/forms/algorithms/custom/Nodes/rs_trigger_node.cpp \
    gui/forms/algorithms/custom/Nodes/trigger_delay_node.cpp \
    gui/forms/algorithms/custom/Nodes/xor_node.cpp \
    gui/forms/algorithms/custom/dep_parser.cpp \
    gui/forms/algorithms/custom/flex_editor_form.cpp \
    gui/forms/algorithms/custom/flexlogic_namespace.cpp \
    gui/forms/main/filesystem_page.cpp \
    gui/forms/input_output/inputs/dins_board_widget.cpp \
    gui/forms/input_output/inputs/dins_external_form.cpp \
    gui/forms/input_output/inputs/dins_logical_form.cpp \
    gui/forms/input_output/inputs/dins_model.cpp \
    gui/forms/input_output/inputs/dins_physical_form.cpp \
    gui/forms/input_output/inputs/dins_virtual_form.cpp \
    gui/forms/algorithms/embedded/algs/MTZ_NN/MTZ_NN_Algorithm.cpp \
    gui/forms/algorithms/embedded/algs/MTZ_SN/MTZ_SN_Algorithm.cpp \
    device_operations/DcUpdateDeviceOperation.cpp \
    gui/forms/thresholds_settings/pqi_event_model.cpp \
    gui/forms/functions/oscillography/AnalogsModel.cpp \
    gui/forms/interfaces_protocols/RS485/TransparentChannel/dc_rs485_transparent_protocol.cpp
